
nagioscheckbeat:
  checks:
    -
      name: "heartbeat"
      cmd: "/usr/lib64/nagios/plugins/check_dummy"
      args: "0 Hello"
    -
      name: "pagestat"
      cmd: "/usr/lib64/nagios/plugins/check_sar_perf.py"
      args: "pagestat"
    -
      name: "io"
      cmd: "/usr/lib64/nagios/plugins/check_sar_perf.py"
      args: "io_transfer"
    -
      name: "memory_util"
      cmd: "/usr/lib64/nagios/plugins/check_sar_perf.py"
      args: "memory_util"
    -
      name: "kernel"
      cmd: "/usr/lib64/nagios/plugins/check_sar_perf.py"
      args: "kernel"
    -
      name: "cpu"
      cmd: "/usr/lib64/nagios/plugins/check_sar_perf.py"
      args: "cpu"
    -
      name: "memory_stat"
      cmd: "/usr/lib64/nagios/plugins/check_sar_perf.py"
      args: "memory_stat"
    -
      name: "queueln_load"
      cmd: "/usr/lib64/nagios/plugins/check_sar_perf.py"
      args: "queueln_load"
    -
      name: "swap_util"
      cmd: "/usr/lib64/nagios/plugins/check_sar_perf.py"
      args: "swap_util"
    -
      name: "swap_stat"
      cmd: "/usr/lib64/nagios/plugins/check_sar_perf.py"
      args: "swap_stat"
    -
      name: "task"
      cmd: "/usr/lib64/nagios/plugins/check_sar_perf.py"
      args: "task"

output.elasticsearch:
  hosts: ["localhost:9200"]