
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported Fields

[partintro]

--
This document describes the fields that are exported by Nagioscheckbeat. They are
grouped in the following categories:

* <<exported-fields-beat>>
* <<exported-fields-nagioscheckbeat>>
* <<exported-fields-nagioscheckcheck>>

--
[[exported-fields-beat]]
== Beat Fields

Contains common beat fields available in all event types.



[float]
=== beat.name

The name of the Beat sending the log messages. If the shipper name is set in the configuration file, then that value is used. If it is not set, the hostname is used.


[float]
=== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[float]
=== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp when the event log record was generated.


[float]
=== tags

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== fields

type: dict

Contains user configurable fields.


[[exported-fields-nagioscheckbeat]]
== NagiosCheckBeat Performance Metrics Fields

None


[float]
=== name

type: keyword

required: True

The name of the check that was executed.  This will match the check's `name` given in configuration.  Each named check might return more than one Performance Metric.


[float]
=== label

type: keyword

required: True

The Performance Metric Label generated by the Nagios Plugin.  For example, this might be the `/dev/hda1` on a disk check.


[float]
=== uom

type: keyword

required: True

As defined in the [Nagios Performance Data guidelines](https://nagios-plugins.org/doc/guidelines.html), UOM or (Unit Of Measure) indicates the metric's unit type.


[float]
=== value

type: double

required: True

The Performance Metric Value returned by the Plugin.  This is the number that represents the current state of the thing being monitored.


[float]
=== min

type: double

required: False

The lower boundary of the range that the value is expected to appear in.  Handy for drawing graphs.  Not required by the plugin if uom=%


[float]
=== max

type: double

required: False

The upper boundary of the range that the value is expected to appear in.  Handy for drawing graphs.  Not required by the plugin if uom=%


[float]
=== warning

type: double

required: False

The warning threshold.  Usually specified in the check arguments and regurgitated here.  The plugin may not always return WARNING when the value is > this threshold, expecially when multiple performance metrics are being tracked.


[float]
=== critical

type: double

required: False

The critical threshold.  Usually specified in the check arguments and regurgitated here.  The plugin may not always return CRITICAL when the value is > this threshold, expecially when multiple performance metrics are being tracked.


[[exported-fields-nagioscheckcheck]]
== NagiosCheckBeat Check Results Fields

None


[float]
=== message

type: text

required: True

The check result message string, as returned from the Nagios plugin.


[float]
=== status

type: keyword

required: True

The check result's String form status.  Will be one of OK, WARNING, CRITICAL, UNKNOWN, or "INVALID STATUS"


[float]
=== status_code

type: integer

required: True

The check result's Integer form status.  Should be 0, 1, 2, or 3, if the Plugin conformed to the standard.


[float]
=== took_ms

type: long

required: True

How long the plugin took to execute, in Milliseconds, measured by NagiosCheckBeat.


