
////
This file is generated! See _meta/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported fields

[partintro]

--
This document describes the fields that are exported by nagioscheckbeat. They are
grouped in the following categories:

* <<exported-fields-beat>>
* <<exported-fields-cloud>>
* <<exported-fields-docker-processor>>
* <<exported-fields-kubernetes-processor>>
* <<exported-fields-nagioscheckbeat>>
* <<exported-fields-nagioscheckcheck>>

--
[[exported-fields-beat]]
== Beat fields

Contains common beat fields available in all event types.



[float]
=== `beat.name`

The name of the Beat sending the log messages. If the Beat name is set in the configuration file, then that value is used. If it is not set, the hostname is used. To set the Beat name, use the `name` option in the configuration file.


[float]
=== `beat.hostname`

The hostname as returned by the operating system on which the Beat is running.


[float]
=== `beat.timezone`

The timezone as returned by the operating system on which the Beat is running.


[float]
=== `beat.version`

The version of the beat that generated this event.


[float]
=== `@timestamp`

type: date

example: August 26th 2016, 12:35:53.332

format: date

required: True

The timestamp when the event log record was generated.


[float]
=== `tags`

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== `fields`

type: object

Contains user configurable fields.


[float]
== error fields

Error fields containing additional info in case of errors.



[float]
=== `error.message`

type: text

Error message.


[float]
=== `error.code`

type: long

Error code.


[float]
=== `error.type`

type: keyword

Error type.


[[exported-fields-cloud]]
== Cloud provider metadata fields

Metadata from cloud providers added by the add_cloud_metadata processor.



[float]
=== `meta.cloud.provider`

example: ec2

Name of the cloud provider. Possible values are ec2, gce, or digitalocean.


[float]
=== `meta.cloud.instance_id`

Instance ID of the host machine.


[float]
=== `meta.cloud.instance_name`

Instance name of the host machine.


[float]
=== `meta.cloud.machine_type`

example: t2.medium

Machine type of the host machine.


[float]
=== `meta.cloud.availability_zone`

example: us-east-1c

Availability zone in which this host is running.


[float]
=== `meta.cloud.project_id`

example: project-x

Name of the project in Google Cloud.


[float]
=== `meta.cloud.region`

Region in which this host is running.


[[exported-fields-docker-processor]]
== Docker fields

Docker stats collected from Docker.




[float]
=== `docker.container.id`

type: keyword

Unique container id.


[float]
=== `docker.container.image`

type: keyword

Name of the image the container was built on.


[float]
=== `docker.container.name`

type: keyword

Container name.


[float]
=== `docker.container.labels`

type: object

Image labels.


[[exported-fields-kubernetes-processor]]
== Kubernetes fields

Kubernetes metadata added by the kubernetes processor




[float]
=== `kubernetes.pod.name`

type: keyword

Kubernetes pod name


[float]
=== `kubernetes.namespace`

type: keyword

Kubernetes namespace


[float]
=== `kubernetes.node.name`

type: keyword

Kubernetes node name


[float]
=== `kubernetes.labels`

type: object

Kubernetes labels map


[float]
=== `kubernetes.annotations`

type: object

Kubernetes annotations map


[float]
=== `kubernetes.container.name`

type: keyword

Kubernetes container name


[float]
=== `kubernetes.container.image`

type: keyword

Kubernetes container image


[[exported-fields-nagioscheckbeat]]
== NagiosCheckBeat Performance Metrics fields

None


[float]
=== `name`

type: keyword

required: True

The name of the check that was executed.  This will match the check's `name` given in configuration.  Each named check might return more than one Performance Metric.


[float]
=== `label`

type: keyword

required: True

The Performance Metric Label generated by the Nagios Plugin.  For example, this might be the `/dev/hda1` on a disk check.


[float]
=== `uom`

type: keyword

required: True

As defined in the [Nagios Performance Data guidelines](https://nagios-plugins.org/doc/guidelines.html), UOM or (Unit Of Measure) indicates the metric's unit type.


[float]
=== `value`

type: double

required: True

The Performance Metric Value returned by the Plugin.  This is the number that represents the current state of the thing being monitored.


[float]
=== `min`

type: double

required: False

The lower boundary of the range that the value is expected to appear in.  Handy for drawing graphs.  Not required by the plugin if uom=%


[float]
=== `max`

type: double

required: False

The upper boundary of the range that the value is expected to appear in.  Handy for drawing graphs.  Not required by the plugin if uom=%


[float]
=== `warning`

type: double

required: False

The warning threshold.  Usually specified in the check arguments and regurgitated here.  The plugin may not always return WARNING when the value is > this threshold, expecially when multiple performance metrics are being tracked.


[float]
=== `critical`

type: double

required: False

The critical threshold.  Usually specified in the check arguments and regurgitated here.  The plugin may not always return CRITICAL when the value is > this threshold, expecially when multiple performance metrics are being tracked.


[[exported-fields-nagioscheckcheck]]
== NagiosCheckBeat Check Results fields

None


[float]
=== `message`

type: text

required: True

The check result message string, as returned from the Nagios plugin.


[float]
=== `status`

type: keyword

required: True

The check result's String form status.  Will be one of OK, WARNING, CRITICAL, UNKNOWN, or "INVALID STATUS"


[float]
=== `status_code`

type: integer

required: True

The check result's Integer form status.  Should be 0, 1, 2, or 3, if the Plugin conformed to the standard.


[float]
=== `took_ms`

type: long

required: True

How long the plugin took to execute, in Milliseconds, measured by NagiosCheckBeat.


